### ISSUE TITLE
Where is the best place to ask general questions?

### ISSUE THREAD

**Issue by JobLeonard** [stardustjs/stardustjs.github.io#4]
I open this as an issue here, since any answer to this should probably be linked from the website ;)

Is there a chatroom or forum planned somewhere to create a community for using Stardust? I'm asking because I have a few questions that wouldn't be appropriate as issues on github (since they're not bugs in the software).

Cheers,
Job

**Comment by donghaoren** [comment]
Hi Job, sorry for a late reply and thanks for your interest! Do you have a suggestion? How about google groups?

Best wishes,
Donghao

**Comment by JobLeonard** [comment]
No worries :)

Google groups would work for me!

**Comment by donghaoren** [comment]
I just created a google groups for discussion (https://groups.google.com/forum/#!forum/stardustjs) feel free to post there!

**Comment by JobLeonard** [comment]
Thanks!
